// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("B2Uploader")]
[assembly: GuidAttribute("a5d41169-c2ee-4b5e-a2d8-b63e485597a6")]
[assembly: AssemblyProductAttribute("B2 Uploader")]
[assembly: AssemblyCompanyAttribute("Tiernan OToole")]
[assembly: AssemblyCopyrightAttribute("TIernan OToole 2016")]
[assembly: AssemblyVersionAttribute("2016.2.1.866")]
[assembly: AssemblyFileVersionAttribute("2016.2.1.866")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2016.2.1.866";
    }
}
