// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("B2Classes")]
[assembly: GuidAttribute("fe353639-3b33-44de-9147-45b63818d8a7")]
[assembly: AssemblyProductAttribute("B2 Uploader")]
[assembly: AssemblyCompanyAttribute("Tiernan OToole")]
[assembly: AssemblyCopyrightAttribute("TIernan OToole 2016")]
[assembly: AssemblyVersionAttribute("2016.2.1.866")]
[assembly: AssemblyFileVersionAttribute("2016.2.1.866")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2016.2.1.866";
    }
}
